language: java
jdk:
  - openjdk7

env:
  global:
    - secure: "Si+FksmD04Qev09hkYqWYN4rYQderrvMt6/kZBTgEek/v4Bd8QVCcbkZemYQCLnfhm94fNJDVrvpbrZhkeSWhCXKnnsYMH9oaxQWSd4aUI55V9QAseVAWMod5d2TSD7kTIo1owV5xh9LHTLmwnv4v6WmV3dSHSQc0zQh09dFC/M="
    - secure: "IVcJyf13GCwLkpYKqygwTH9f3EG1YiqdmXWPCt5d9DXKKLjbSq/MFQ/nwdgfgfJAsgrSXN0I+6fIf8/INtI4YcKTpzAblXdeAkWdVrD4xpRSC7TpEHdEGMWEBtSWzJy8b92F2cxCXuk/QPDK4d8/QuelkFD9C9IztmgSqq7fQQg="

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq sshpass
 - echo "graphwalker.org,62.75.191.213 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAtt0gW2tGz1f60qs4mSteVq+AhWAw7xYak3+UegaWSwxVh9MpqG/JDRF5CpzTiUvyXlhlAYZ6kCVT5G4zXNNC7ty9UuA5D2PicGOWsF73KGLu6GbmRQTrTMf5ji/IkrFoJysNaXPIbqkwX0TB3DoTyXfE/HoP2JSGwVi5tztUaOc=" > ~/.ssh/known_hosts

install:
  mvn install -DskipTests=true -Dgpg.skip=true

script:
  mvn package -DskipTests=true -Dgpg.skip=true

after_success:
  - pwd
  - ls -ltr
  - ls -ltr target
  - ls -ltr /home/travis/build/KristianKarl/GraphWalker/
  - ls -ltr /home/travis/build/KristianKarl/GraphWalker/target
  - sshpass -p $GW_PASSWORD scp /home/travis/build/KristianKarl/GraphWalker/target/graphwalker-*.jar $GW_USER@graphwalker.org:/var/www/data/uploads/
